# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 18:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('desc', models.TextField()),
                ('min_price', models.FloatField()),
                ('deadline', models.DateTimeField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('modifiedAt', models.DateTimeField(auto_now=True)),
                ('authName', models.CharField(max_length=300)),
                ('tala', models.NullBooleanField()),
                ('is_banned', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auction',
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('auction', models.IntegerField()),
                ('auctioner', models.CharField(max_length=300)),
                ('bidder', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'bid',
            },
        ),
    ]
