# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_cron', '0002_remove_max_length_from_CronJobLog_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cronjoblog',
            old_name='auction',
            new_name='id',
        ),
    ]
